# Game settings
MINING_COOLDOWN = 300  # 5 minutes
TRAINING_COOLDOWN = 600  # 10 minutes
DAILY_RESET_TIME = '00:00'  # UTC
MAX_ENERGY = 100
ENERGY_REGEN_RATE = 1  # per minute
ENERGY_REGEN_INTERVAL = 60  # seconds

# Experience settings
EXP_PER_LEVEL = 1000
MINING_EXP = 50
TRAINING_EXP = 100

# Reward settings
MINING_BASE_REWARD = 10
TRAINING_BASE_REWARD = 20
DAILY_BASE_REWARD = 100
